### ISSUE TITLE
Adjust temperature automatically based on location

### ISSUE THREAD

**Issue by ronilaukkarinen** [Fushko/gammy#60] opened 2020-12-28 20:40 UTC
I like the simplicity of this app and the adaptive brightness feature that f.lux doesn't have. However, In Finland the daylight changes often so I need to adjust times many times a year. So here's a feature request: Get daylight times based on location input to adjust times automatically. Any chance to implement this?

**Comment by Fushko** [comment] 2020-12-29 07:51
Yes. Duplicate of #17

**Closed by Fushko** 2020-12-29 07:51 UTC
