### ISSUE TITLE
Major issue with gammy when used before preconfigured Auto settings

### ISSUE THREAD

**Issue by stefanos82** [Fushko/gammy#79] opened 2021-01-16 13:55 UTC
I had originally set my settings to `Auto` for temperature and brightness set to fixed 80%.

Today I decided to start it before the preset time which starts at 16:00 local time and guess what; everything has been reset to default settings by discarding my customizations.

Update: I have just noticed it affects how my whole graphics rendering behaves.

When I move the mouse, it crawls on its knees and makes my XFCE4 very unstable as a whole.

As soon as I turn gammy off, everything returns back to normal.

**Comment by Fushko** [comment] 2021-01-17 09:22
> Today I decided to start it before the preset time which starts at 16:00

Sunrise or sunset?

> everything has been reset to default settings by discarding my customizations.

Everything? All the sliders are reset?

> When I move the mouse, it crawls on its knees and makes my XFCE4 very unstable as a whole.

With auto brightness on or off? What's your screenshot rate?

Also which version?

**Comment by stefanos82** [comment] 2021-01-17 11:33
> > Today I decided to start it before the preset time which starts at 16:00
> 
> Sunrise or sunset?

I'm not sure I follow here...you do know that 16:00 is 4PM based on 24-hour clock, don't you?

> > everything has been reset to default settings by discarding my customizations.
> 
> Everything? All the sliders are reset?
>

Yep, literally everything. 

> > When I move the mouse, it crawls on its knees and makes my XFCE4 very unstable as a whole.
> 
> With auto brightness on or off? Auto temperature on or off? What's your screenshot rate?
>

Auto  brightness off, but set to 50% on its own, even though the checkbox is unchecked.

> Also which version?

The latest HEAD.

I would suggest the following: when we compile from main repo or any other branch, it would be helpful to append the commit hash next to version number.

This way we can be more specific towards which commit version the issue takes place.

**Comment by stefanos82** [comment] 2021-01-17 11:35
Another interesting behavior is the following: after 16:00 (4PM), if I decide to run gammy, my own settings take place and everything behaves as expected.

But if I run it before the preset time settings, it behaves as I have mentioned above.

**Comment by Fushko** [comment] 2021-01-17 15:20
1. I can't reproduce the config not applying before the sunset time is reached, but applying after.
2. You get performance issues even with all auto checkboxes off?

**Comment by stefanos82** [comment] 2021-01-17 15:30
>     2. You get performance issues even with all auto checkboxes off?

It happened when I run it before 4PM sunset time. I have changed the time now to reproduce it but with negative results.

I have no idea how that happened, really.

**Comment by Fushko** [comment] 2021-01-17 18:43
Okay, so the lag issue was just a one time thing apparently.
Still, the first bug you're describing doesn't make any sense, the config doesn't get parsed any differently when it's past the sunset time. In fact the two things aren't related in the slightest. Maybe I didn't understand the issue properly?

**Comment by stefanos82** [comment] 2021-01-17 19:09
> Still, the first bug you're describing doesn't make any sense, the config doesn't get parsed any differently when it's past the sunset time. In fact the two things aren't related in the slightest. Maybe I didn't understand the issue properly?

OK, let me describe it a bit better.

Because it was raining and was very dark from 3PM local time, I decided to start gammy.

As I have mentioned before, my sunset settings should take place at 4PM local time, with adaptation time of 10 minutes.

When I run gammy at 3:45PM to be precise, it behaved as if I never had any custom settings before.

The weirdest thing was how Brightness was behaving; the Auto was unchecked, but it would auto-arrange brightness on its own.

The Range was set between 50% to 100%, even though the Auto was off and should have stayed at 80% fixed setting.

**Comment by Fushko** [comment] 2021-01-17 19:17
> The weirdest thing was how Brightness was behaving; the Auto was unchecked, but it would auto-arrange brightness on its own.

This is some weirdness that can happen with Qt sometimes. Toggling the checkbox, or a restart usually fix these.

Just to be clear, the issue only happened one time right? It's not happened anymore since?

**Comment by stefanos82** [comment] 2021-01-17 19:21
> This is some weirdness that can happen with Qt sometimes. Toggling the checkbox, or a restart usually fix these.
> 
> Just to be clear, the issue only happened one time right? It's not happened anymore since?

Yes, it happened only once.

Tomorrow though, I will try to run it before 4PM to see how it will behave.

If the same behavior repeat itself, I will report it here.

**Comment by stefanos82** [comment] 2021-01-18 12:45
I have just tested it and works normally.

I honestly have no idea what caused that glitch...on the other hand, I had a different version compiled when I reported this.

Then you pushed a couple of minor changes and compiled those versions sequentially.

Maybe was something that was taking place in those commits? :shrug:

**Comment by Fushko** [comment] 2021-01-18 19:57
Okay, I'll close this for now.

**Closed by Fushko** 2021-01-18 19:57 UTC
